### ISSUE TITLE
Could you give an example for a pair of images?

### ISSUE THREAD

**Issue by cxmscb** [Gabriel-SGama/Semantic-SuperPoint#2]
Could you give an example for a pair of images? Thx.
And what is the difference between superpoint_coco_2017_ML22 and superpoint_coco_ssmall_ML22?

**Comment by Gabriel-SGama** [comment]
First, relating to the image example, do you want something like this? This was generated using the evaluation code already present in the pytorch-Superpoint repository. The amount of matches are limited for better visualization. 

![0m](https://user-images.githubusercontent.com/41309763/224509026-8dbd1bb8-05ba-479c-80e0-22c9b44459d7.png)

Regarding to the differences of the models, the **superpoint_coco_2017_ML22** wasn't trained with the semantic decoder and **superpoint_coco_ssmall_ML22** was. Both were trained using the uncertainty weighted loss. The subscripts ssmall and ML22 are related to the semantic decoder and loss version used, respectively.

**Comment by cxmscb** [comment]
> First, relating to the image example, do you want something like this? This was generated using the evaluation code already present in the pytorch-Superpoint repository. The amount of matches are limited for better visualization.
> 
> ![0m](https://user-images.githubusercontent.com/41309763/224509026-8dbd1bb8-05ba-479c-80e0-22c9b44459d7.png)
> 
> Regarding to the differences of the models, the **superpoint_coco_2017_ML22** wasn't trained with the semantic decoder and **superpoint_coco_ssmall_ML22** was. Both were trained using the uncertainty weighted loss. The subscripts ssmall and ML22 are related to the semantic decoder and loss version used, respectively.

Thanks, and which code contains the network of superpoint_coco_2017_ML22?
