### ISSUE TITLE
Convert the weights of the pre-trained models to pth format

### ISSUE THREAD

**Issue by Gpetrak** [Gabriel-SGama/Semantic-SuperPoint#4]
At first I'd like to thank you for this great work !
I want to test your pre-trained models in an implementation that uses .pth files instead of pth.tar. Thus, I tried your script "convert2script.py" in order to convert the weights to a pth model but it raises the following error:

RuntimeError: logs/superpoint_coco_ssmall_ML22/checkpoints/superPointNet_180000_checkpoint.pth.tar is a zip archive (did you mean to use torch.jit.load()?)

As I read, a possible reason is that the version of Pytorch that the model was trained is different with the installed Pytorch version. I'm using Pytorch 1.3.1 since this is the tested version for your implementation.
What version did you use to train the proposed pre-trained models ? Is the Pytorch=1.3.1 the recommended version ?

**Comment by Gabriel-SGama** [comment]
Thank you for your interest. The script convert2script.py converts the weights from the checkpoint.pth.tar file to a .pt to use it on C++ with the torch library, so actually, you only need to use it until the `model.load_state_dict(torch.load(path)["model_state_dict"])` line to convert to a state dict to your model. After doing this, you can convert it to a .pth file for convenience.

Regarding the RuntimeError, you are probably right. I just checked and the Pytorch version on the environment is 1.9.0+cu111. Could you try changing the Pytorch version solves the issue? If this solves the problem, I will change the README to recommend this version instead.

**Comment by Gpetrak** [comment]
Thank you for your prompt answer.At first I'd like to try your implementation with Pytorch 1.3.1 (training and evaluation) because the compatible Cuda version (10.0) is used in other implementations of my system also. But as soon as possible, I'll try with a newer version of Pytorch and Cuda.

**Comment by Gpetrak** [comment]
I changed the Pytorch version to 1.9.0 with CUDA 11.2 and the problem solved.
Thus, I can confirm that this codebase is compatible with Pytorch 1.9.0 and CUDA 11.2.
