### ISSUE TITLE
question about train4

### ISSUE THREAD

**Issue by ZhHaoH** [Gabriel-SGama/Semantic-SuperPoint#6]
When I run train4.py, the error shows that no module named "Train_model_heatmap", and I change the front_end_model in "magicpoint_shapes_pair" to "Train_model_heatmap_all", and then the following error occurred:
Traceback (most recent call last).
  File "semanticSP/train4.py", line 143, in <module>
    args.func(config, output_dir, args)
  File "semanticSP/train4.py", line 44, in train_base
    return train_joint(config, output_dir, args)
  File "semanticSP/train4.py", line 83, in train_joint
    train_agent = train_model_frontend(config, save_path=save_path, device=device)
  File "semanticSP/Train_model_heatmap_all.py", line 108, in __init__
    self.r = self.config["model"]["real_batch_size"] // self.config["model"]["batch_size"]
KeyError: 'real_batch_size'
What is the problem?

**Comment by Gabriel-SGama** [comment]
I didn't use the config file magicpoint_shapes_pair in my tests, but this variable was used to mimic a bigger batch size than the one allowed by memory https://discuss.pytorch.org/t/why-do-we-need-to-set-the-gradients-manually-to-zero-in-pytorch/4903/20 (in the end, I only used self.r = 1 for my training, but you could config it in the way you like).

As I didn't use this file, probably other fields are missing. To fix you only need to add the respective field or remove the code related to it.

**Comment by ZhHaoH** [comment]
So magicpoint you are using the trained model directly? train4 code is mainly using coco dataset to train semantic superpoint?

**Comment by Gabriel-SGama** [comment]
For the keypoint extraction I used the pretrained model `logs/magicpoint_synth20/checkpoints/superPointNet_200000_checkpoint.pth.tar`. 

Yes, the `train4.py` code is mainly used to train the superpoint (both the semantic and non semantic versions)

**Comment by ZhHaoH** [comment]
Ok, thank you
